/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
package Images;

import Data.HoaDon;
import Data.SanPham;
import JDBC_Connection.SolveHoaDon;
import JDBC_Connection.SolveSanPham;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultTableModel defaultTableModel;
    public MainFrame() {
        initComponents();
        //jPanel1.setSize(400,400);
        this.setSize(1200,615);
        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT,16,6));
        this.getContentPane().setBackground(new java.awt.Color(255, 250, 205));
        //this.add(jPanel1);
        createButtonFull();
        xuatTable();
        JLabel jLabel1=new JLabel();
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflarewallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        manePanel1.add(jLabel1);
        JViewport viewport=new JViewport();
        viewport.setOpaque(false);
        //viewport.set
        //jScrollPane2.setViewport(new JViewport());
        jScrollPane2.getViewport().setOpaque(false);
        jLabel1.setBounds(0, 0, 1200, 590);
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
    }
    
    public void xuatTable(){
        defaultTableModel=new DefaultTableModel();
        hoaDonTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("Ten");
        defaultTableModel.addColumn("Ma");
        defaultTableModel.addColumn("Kich co");
        defaultTableModel.addColumn("Don gia");
        defaultTableModel.addColumn("So Luong");
        defaultTableModel.addColumn("Tong");
        ArrayList<HoaDon> A=new ArrayList<>();
        A=SolveHoaDon.getAllHoaDon();
        for(HoaDon p : A){
            defaultTableModel.addRow(new Object[]{p.getStt(),p.getName(),p.getSize(),p.getPrice(),p.getSoLuong(),p.getSum()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manePanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sumButton = new javax.swing.JButton();
        sumLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hoaDonTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        manePanel1.setBackground(new java.awt.Color(255, 250, 205));
        manePanel1.setMaximumSize(new java.awt.Dimension(800, 400));
        manePanel1.setPreferredSize(new java.awt.Dimension(1190, 350));
        manePanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 250, 205));

        sumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_receipt_long_black_24dp.png"))); // NOI18N
        sumButton.setText("Thanh toán");
        sumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumButtonActionPerformed(evt);
            }
        });

        sumLabel.setBackground(new java.awt.Color(255, 228, 181));
        sumLabel.setText("0");

        refreshButton.setText("Cập nhật");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xoá");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Sửa");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        hoaDonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        hoaDonTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        hoaDonTable.setShowGrid(false);
        jScrollPane1.setViewportView(hoaDonTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sumButton)
                            .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshButton)
                            .addComponent(deleteButton)
                            .addComponent(editButton))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        manePanel1.add(jPanel2);
        jPanel2.setBounds(0, 420, 1190, 168);

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 460));
        jScrollPane2.setViewportView(jPanel1);

        manePanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1200, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        ArrayList<HoaDon> A=new ArrayList<>();
        A=SolveHoaDon.getAllHoaDon();
        for(HoaDon p : A){
            defaultTableModel.addRow(new Object[]{p.getStt(),p.getName(),p.getMa(),p.getSize(),p.getPrice(),p.getSoLuong(),p.getSum()});
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void sumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumButtonActionPerformed
        sumLabel.setText(String.valueOf(SolveHoaDon.sumHoaDon()));
        try {
            File f = new File("/Users/mac/Desktop/Java/HoaDon.txt");
            FileWriter fw = new FileWriter(f);
            String s ="----------------------Hoa don thanh toan---------------------"+"\n";
            //s += "Hinh thuc thanh toan:                                    Ngay:       ";// 36
            Date tmpDate= new Date();
            DateFormat dateFormat=new SimpleDateFormat("dd-MM-yyyy");
            DateFormat dateFormat2=new SimpleDateFormat("hh:mm");
            String ngay = dateFormat.format(tmpDate);
            String ban = "Ban mang ve";
            s=s+"Hinh thuc thanh toan: "+ban;
            for(int i=0;i<23-ban.length();i++)
                s=s+" ";
            s+="Ngay: "+ngay+"\n";
            s+="Gio vao: ";
            String gio=dateFormat2.format(tmpDate);
            s+=gio;
            for(int i=1;i<=34;i++)
                s+=" ";
            s+="Gio ra: "+gio+"\n";
            s += "-------------------------------------------------------------" + "\n";
            s +="STT   Ten san pham               SL      Don gia   Thanh tien" + "\n";// 6-27-8-10
            String tmp = "STT   Ten san pham               SL      Don gia   ";
            //System.out.println(tmp.length());
            ArrayList<HoaDon> hoaDons=JDBC_Connection.SolveHoaDon.getAllHoaDon();
            for(HoaDon hoaDon:hoaDons){
                ArrayList<String> A = new ArrayList<>();
                A.add(String.valueOf(hoaDon.getStt()));
                A.add(hoaDon.getName());
                A.add(String.valueOf(hoaDon.getSoLuong()));
                A.add(String.valueOf(hoaDon.getPrice()));
                s = s + A.get(0);
                for (int i = 0; i < 6 - A.get(0).length(); i++)
                    s = s + " ";
                s = s + A.get(1);
                for (int i = 0; i < 27 - A.get(1).length(); i++)
                    s = s + " ";
                s = s + A.get(2);
                for (int i = 0; i < 8 - A.get(2).length(); i++)
                    s = s + " ";
                s = s + A.get(3);
                for (int i = 0; i < 10 - A.get(3).length(); i++)
                    s = s + " ";
                s = s + String.valueOf(Integer.parseInt(A.get(2)) * Integer.parseInt(A.get(3)))+"\n";
                // System.out.println(s.length());//56                
            }
            fw.write(s);
            s ="Tong: ";
            for(int i=0;i<45;i++){
                s=s+" ";
            }
            int sum=SolveHoaDon.sumHoaDon();
            s=s+String.valueOf(sum)+"\n"+"\n";

            s=s+ "-------------------------------------------------------------"+"\n";
            fw.write(s);
            s  ="                       Coffee Name                           "+"\n";
            s +="      Dia chi: 54 Ly Chieu Hoang, Suoi Hoa ,Tp Bac Ninh      "+"\n";
            s +="                   So hotline: 0123456789                    "+"\n";
            s +="                     Wifi: coffeeName                        "+"\n";
            s +="                     MK wifi: password                       "+"\n";
            fw.write(s);
              fw.close();
            } catch (IOException ex) {
                System.out.println("Loi ghi file: " + ex);
            }
    }//GEN-LAST:event_sumButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row=hoaDonTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(MainFrame.this,"Vui long chon hoa don can xoa","Loi",JOptionPane.ERROR_MESSAGE);
        }else{
            int confirm=JOptionPane.showConfirmDialog(MainFrame.this,"Ban muon xoa khong");
            if(confirm==JOptionPane.YES_OPTION){
                int stt=Integer.valueOf(String.valueOf(hoaDonTable.getValueAt(row,0)));
                SolveHoaDon.deleteHoaDon(stt);
                defaultTableModel.setRowCount(0);
                ArrayList<HoaDon> A=new ArrayList<>();
                A=SolveHoaDon.getAllHoaDon();
                for(HoaDon p : A){
                    defaultTableModel.addRow(new Object[]{p.getStt(),p.getName(),p.getMa(),p.getSize(),p.getPrice(),p.getSoLuong(),p.getSum()});
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        int row=hoaDonTable.getSelectedRow();
        int stt=Integer.parseInt(String.valueOf(hoaDonTable.getValueAt(row,0)));
        HoaDon hoaDon=SolveHoaDon.getHoaDon(stt);
        new EditFrame(hoaDon).setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTable hoaDonTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel manePanel1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton sumButton;
    private javax.swing.JLabel sumLabel;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void createButton(String code, String name){
        JButton p=new JButton(name);
        p.setVerticalTextPosition(SwingConstants.BOTTOM);//xét vị trí text theo chiều thẳng-vị trí dưới
        p.setHorizontalTextPosition(SwingConstants.CENTER);//xét vị trí text theo chiều ngang-vị trí trung tâm
        //Icon icon=new ImageIcon("/Users/mac/Desktop/Java/BTL/src/Images/coffee.png");
        if(code.charAt(0)=='C'){
            //Icon icon=new ImageIcon("/Users/mac/Desktop/Java/BTL/src/Images/coffee.png");
            p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee.png"))); // NOI18N
            //p.setIcon(icon);
        } else if(code.charAt(0)=='T'){
//            Icon icon=new ImageIcon("/Users/mac/Desktop/Java/BTL/src/Images/milk-tea.png");
//            p.setIcon(icon);
            p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/milk-tea.png"))); // NOI18N
        } else{
            p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bread.png"))); // NOI18N
//            Icon icon=new ImageIcon("/Users/mac/Desktop/Java/BTL/src/Images/bread.png");
//            p.setIcon(icon);
        }
        //p.setIcon(icon);
        jPanel1.add(p);
        p.addActionListener(new ButtonListener(code));
    }
    public class ButtonListener implements ActionListener{
        private String s;
        public ButtonListener(String s){
            this.s=s;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            new NhapFrame(s).setVisible(true);
        }
        
    }
    public void createButtonFull(){
        ArrayList<SanPham> A=new ArrayList<>();
        A=SolveSanPham.getAllSanPham();
        for(SanPham i : A){
            createButton(i.getCode(),i.getName());
        }
    }
}
